added PR conventions
python-sprints/pandas-mentoring pull request #113
Opened 2019-08-10 15:28 UTC by Yomdroid

2019-08-11 10:59 UTC, galuhsahid commented on contributing.md
> +Discovering an issue is great, here's what you need to do when you discover an issue;
I think "an issue;" should be "an issue:"

2019-08-11 10:59 UTC, galuhsahid commented on contributing.md
> +<br>
We probably don't need a `<br>` here, I think leaving the line blank would give the same effect

2019-08-11 10:59 UTC, galuhsahid commented on contributing.md
> +<br>
We probably don't need a `<br>` here, I think leaving the line blank would give the same effect

2019-08-11 10:59 UTC, galuhsahid commented on contributing.md
>  <br>
I see that this is from the previous PR, maybe we can remove the `br` here too?

2019-08-13 11:15 UTC, sara-02 requested changes

2019-08-13 11:15 UTC, sara-02 commented on contributing.md
> +## Reporting bugs
Reporting bugs should be a subcategory of the issues, please move it under the Issues. And make its header `###`

2019-08-13 11:15 UTC, sara-02 commented on contributing.md
> +## Issues
Maybe label the heading as  `Issue Guidelines`?

2019-08-13 11:15 UTC, sara-02 commented on contributing.md
> +<br>
remove the `<br>` from here as well.

2019-08-13 11:16 UTC, sara-02 commented
@Yomdroid Both I and @galuhsahid have requested a few changes, please look into them.

2019-08-14 13:19 UTC, Yomdroid commented
@sara-02 @galuhsahid changes made in  14e8e07

2019-08-14 20:32 UTC, dujm approved these changes

2019-08-15 08:05 UTC, sara-02 approved these changes

2019-08-15 08:06 UTC, merged

2019-08-15 08:06 UTC, sara-02 commented
@Yomdroid Thanks.